const wordDB_toefl = [
    { "word": "abandon", "ipa": "əˈbændən", "meanings": { "ko": "버리다, 포기하다", "ja": "放棄する", "zh": "放弃", "es": "abandonar", "fr": "abandonner", "de": "verlassen", "ru": "оставлять" } },
    { "word": "accommodate", "ipa": "əˈkɑːmədeɪt", "meanings": { "ko": "수용하다, 편의를 제공하다", "ja": "収容する", "zh": "容纳", "es": "acomodar", "fr": "accueillir", "de": "unterbringen", "ru": "вмещать" } },
    { "word": "analyze", "ipa": "ˈænəlaɪz", "meanings": { "ko": "분석하다", "ja": "分析する", "zh": "分析", "es": "analizar", "fr": "analyser", "de": "analysieren", "ru": "анализировать" } },
    { "word": "bias", "ipa": "ˈbaɪəs", "meanings": { "ko": "편견, 편향", "ja": "偏見", "zh": "偏见", "es": "sesgo", "fr": "biais", "de": "Voreingenommenheit", "ru": "предвзятость" } },
    { "word": "coherent", "ipa": "koʊˈhɪrənt", "meanings": { "ko": "일관성 있는, 논리적인", "ja": "首尾一貫した", "zh": "连贯的", "es": "coherente", "fr": "cohérent", "de": "kohärent", "ru": "связный" } },
    { "word": "critique", "ipa": "krɪˈtiːk", "meanings": { "ko": "비평하다, 비판", "ja": "批評", "zh": "评论", "es": "crítica", "fr": "critique", "de": "Kritik", "ru": "критика" } },
    { "word": "diverse", "ipa": "daɪˈvɝs", "meanings": { "ko": "다양한", "ja": "多様な", "zh": "多样化的", "es": "diverso", "fr": "divers", "de": "vielfältig", "ru": "разнообразный" } },
    { "word": "enhance", "ipa": "ɪnˈhæns", "meanings": { "ko": "향상시키다", "ja": "高める", "zh": "提高", "es": "mejorar", "fr": "améliorer", "de": "verbessern", "ru": "улучшать" } },
    { "word": "feasible", "ipa": "ˈfiːzəbəl", "meanings": { "ko": "실현 가능한", "ja": "実現可能な", "zh": "可行的", "es": "factible", "fr": "faisable", "de": "machbar", "ru": "осуществимый" } },
    { "word": "innovative", "ipa": "ˈɪnəveɪtɪv", "meanings": { "ko": "혁신적인", "ja": "革新的な", "zh": "创新的", "es": "innovador", "fr": "innovant", "de": "innovativ", "ru": "инновационный" } },
    { "word": "acknowledge", "ipa": "əkˈnɑːlɪdʒ", "meanings": { "ko": "인정하다, 승인하다", "ja": "認める", "zh": "承认", "es": "reconocer", "fr": "reconnaître", "de": "anerkennen", "ru": "признавать" } },
    { "word": "acquire", "ipa": "əˈkwaɪər", "meanings": { "ko": "획득하다, 얻다", "ja": "取得する", "zh": "获得", "es": "adquirir", "fr": "acquérir", "de": "erwerben", "ru": "приобретать" } },
    { "word": "adapt", "ipa": "əˈdæpt", "meanings": { "ko": "적응하다, 개조하다", "ja": "適応する", "zh": "适应", "es": "adaptar", "fr": "adapter", "de": "anpassen", "ru": "адаптировать" } },
    { "word": "adequate", "ipa": "ˈædɪkwət", "meanings": { "ko": "충분한, 적절한", "ja": "適切な", "zh": "足够", "es": "adecuado", "fr": "adéquat", "de": "ausreichend", "ru": "адекватный" } },
    { "word": "advocate", "ipa": "ˈædvəkeɪt", "meanings": { "ko": "옹호하다, 지지자", "ja": "擁護する", "zh": "提倡", "es": "abogar", "fr": "prôner", "de": "befürworten", "ru": "отстаивать" } },
    { "word": "alter", "ipa": "ˈɔːltər", "meanings": { "ko": "변경하다, 바꾸다", "ja": "変更する", "zh": "改变", "es": "alterar", "fr": "altérer", "de": "ändern", "ru": "изменять" } },
    { "word": "ambiguous", "ipa": "æmˈbɪɡjuəs", "meanings": { "ko": "모호한, 애매한", "ja": "曖昧な", "zh": "模糊不清", "es": "ambiguo", "fr": "ambigu", "de": "zweideutig", "ru": "неоднозначный" } },
    { "word": "anticipate", "ipa": "ænˈtɪsɪpeɪt", "meanings": { "ko": "예상하다, 기대하다", "ja": "予測する", "zh": "预期", "es": "anticipar", "fr": "anticiper", "de": "antizipieren", "ru": "предвидеть" } },
    { "word": "appreciate", "ipa": "əˈpriːʃieɪt", "meanings": { "ko": "평가하다, 이해하다, 감사하다", "ja": "評価する", "zh": "欣赏", "es": "apreciar", "fr": "apprécier", "de": "wertschätzen", "ru": "ценить" } },
    { "word": "approach", "ipa": "əˈproʊtʃ", "meanings": { "ko": "접근하다, 접근법", "ja": "接近する", "zh": "接近", "es": "acercarse", "fr": "approcher", "de": "sich nähern", "ru": "подходить" } },
    { "word": "appropriate", "ipa": "əˈproʊpriət", "meanings": { "ko": "적절한", "ja": "適切な", "zh": "适当的", "es": "apropiado", "fr": "approprié", "de": "angemessen", "ru": "подходящий" } },
    { "word": "arbitrary", "ipa": "ˈɑːrbɪtrɛri", "meanings": { "ko": "임의적인, 독단적인", "ja": "恣意的な", "zh": "任意的", "es": "arbitrario", "fr": "arbitraire", "de": "willkürlich", "ru": "произвольный" } },
    { "word": "assert", "ipa": "əˈsɜːrt", "meanings": { "ko": "주장하다, 단언하다", "ja": "主張する", "zh": "断言", "es": "afirmar", "fr": "affirmer", "de": "behaupten", "ru": "утверждать" } },
    { "word": "assess", "ipa": "əˈsɛs", "meanings": { "ko": "평가하다, 사정하다", "ja": "評価する", "zh": "评估", "es": "evaluar", "fr": "évaluer", "de": "beurteilen", "ru": "оценивать" } },
    { "word": "assume", "ipa": "əˈsuːm", "meanings": { "ko": "가정하다, 추정하다", "ja": "仮定する", "zh": "假设", "es": "asumir", "fr": "supposer", "de": "annehmen", "ru": "предполагать" } },
    { "word": "attain", "ipa": "əˈteɪn", "meanings": { "ko": "달성하다, 이루다", "ja": "達成する", "zh": "达到", "es": "lograr", "fr": "atteindre", "de": "erreichen", "ru": "достигать" } },
    { "word": "attribute", "ipa": "ˈætrɪbjuːt", "meanings": { "ko": "속성, ~의 탓으로 돌리다", "ja": "属性", "zh": "属性", "es": "atributo", "fr": "attribuer", "de": "Attribut", "ru": "приписывать" } },
    { "word": "augment", "ipa": "ɔːɡˈmɛnt", "meanings": { "ko": "증가시키다, 늘리다", "ja": "増加させる", "zh": "增加", "es": "aumentar", "fr": "augmenter", "de": "erhöhen", "ru": "увеличивать" } },
    { "word": "authoritative", "ipa": "əˈθɔːrɪteɪtɪv", "meanings": { "ko": "권위 있는, 확실한", "ja": "権威ある", "zh": "权威的", "es": "autorizado", "fr": "autoritaire", "de": "autoritativ", "ru": "авторитетный" } },
    { "word": "benevolent", "ipa": "bəˈnɛvələnt", "meanings": { "ko": "자비로운, 인자한", "ja": "慈悲深い", "zh": "仁慈的", "es": "benévolo", "fr": "bienveillant", "de": "wohlwollend", "ru": "благосклонный" } },
    { "word": "comprehensive", "ipa": "ˌkɑːmprɪˈhɛnsɪv", "meanings": { "ko": "포괄적인, 종합적인", "ja": "包括的な", "zh": "全面的", "es": "exhaustivo", "fr": "complet", "de": "umfassend", "ru": "всеобъемлющий" } },
    { "word": "concede", "ipa": "kənˈsiːd", "meanings": { "ko": "인정하다, 양보하다", "ja": "認める", "zh": "承认", "es": "conceder", "fr": "concéder", "de": "zugestehen", "ru": "уступать" } },
    { "word": "concise", "ipa": "kənˈsaɪs", "meanings": { "ko": "간결한, 요약된", "ja": "簡潔な", "zh": "简洁", "es": "conciso", "fr": "concis", "de": "prägnant", "ru": "краткий" } },
    { "word": "concur", "ipa": "kənˈkɜːr", "meanings": { "ko": "동의하다, 일치하다", "ja": "同意する", "zh": "同意", "es": "estar de acuerdo", "fr": "être d'accord", "de": "zustimmen", "ru": "соглашаться" } },
    { "word": "confine", "ipa": "kənˈfaɪn", "meanings": { "ko": "한정하다, 가두다", "ja": "限定する", "zh": "限制", "es": "confinar", "fr": "confiner", "de": "beschränken", "ru": "ограничивать" } },
    { "word": "consequence", "ipa": "ˈkɑːnsəkwəns", "meanings": { "ko": "결과, 중요성", "ja": "結果", "zh": "结果", "es": "consecuencia", "fr": "conséquence", "de": "Folge", "ru": "следствие" } },
    { "word": "consistent", "ipa": "kənˈsɪstənt", "meanings": { "ko": "일관된, 변함없는", "ja": "一貫した", "zh": "一致的", "es": "consistente", "fr": "cohérent", "de": "konsistent", "ru": "последовательный" } },
    { "word": "constitute", "ipa": "ˈkɑːnstɪtuːt", "meanings": { "ko": "~을 구성하다, 설립하다", "ja": "構成する", "zh": "构成", "es": "constituir", "fr": "constituer", "de": "bilden", "ru": "составлять" } },
    { "word": "constrain", "ipa": "kənˈstreɪn", "meanings": { "ko": "강요하다, 억제하다", "ja": "制約する", "zh": "限制", "es": "restringir", "fr": "contraindre", "de": "einschränken", "ru": "ограничивать" } },
    { "word": "contend", "ipa": "kənˈtɛnd", "meanings": { "ko": "주장하다, 다투다", "ja": "争う", "zh": "争论", "es": "contender", "fr": "contester", "de": "streiten", "ru": "бороться" } },
    { "word": "context", "ipa": "ˈkɑːntɛkst", "meanings": { "ko": "맥락, 상황", "ja": "文脈", "zh": "语境", "es": "contexto", "fr": "contexte", "de": "Kontext", "ru": "контекст" } },
    { "word": "contradict", "ipa": "ˌkɑːntrəˈdɪkt", "meanings": { "ko": "반박하다, 모순되다", "ja": "矛盾する", "zh": "矛盾", "es": "contradecir", "fr": "contredire", "de": "widersprechen", "ru": "противоречить" } },
    { "word": "controversy", "ipa": "ˈkɑːntrəvɜːrsi", "meanings": { "ko": "논쟁, 논란", "ja": "論争", "zh": "争议", "es": "controversia", "fr": "controverse", "de": "Kontroverse", "ru": "спор" } },
    { "word": "convene", "ipa": "kənˈviːn", "meanings": { "ko": "소집하다, 모이다", "ja": "招集する", "zh": "召集", "es": "convocar", "fr": "convoquer", "de": "einberufen", "ru": "созывать" } },
    { "word": "correlate", "ipa": "ˈkɔːrəleɪt", "meanings": { "ko": "상관관계가 있다", "ja": "相関する", "zh": "相关", "es": "correlacionar", "fr": "corréler", "de": "korrelieren", "ru": "соотноситься" } },
    { "word": "crucial", "ipa": "ˈkruːʃəl", "meanings": { "ko": "결정적인, 중대한", "ja": "極めて重要な", "zh": "关键的", "es": "crucial", "fr": "crucial", "de": "entscheidend", "ru": "ключевой" } },
    { "word": "deduce", "ipa": "dɪˈduːs", "meanings": { "ko": "추론하다, 연역하다", "ja": "推論する", "zh": "推断", "es": "deducir", "fr": "déduire", "de": "ableiten", "ru": "выводить" } },
    { "word": "define", "ipa": "dɪˈfaɪn", "meanings": { "ko": "정의하다", "ja": "定義する", "zh": "定义", "es": "definir", "fr": "définir", "de": "definieren", "ru": "определять" } },
    { "word": "demonstrate", "ipa": "ˈdɛmənstreɪt", "meanings": { "ko": "입증하다, 시연하다", "ja": "実証する", "zh": "证明", "es": "demostrar", "fr": "démontrer", "de": "demonstrieren", "ru": "демонстрировать" } },
    { "word": "depict", "ipa": "dɪˈpɪkt", "meanings": { "ko": "묘사하다, 그리다", "ja": "描写する", "zh": "描绘", "es": "describir", "fr": "dépeindre", "de": "darstellen", "ru": "изображать" } },
    { "word": "derive", "ipa": "dɪˈraɪv", "meanings": { "ko": "~을 얻다, 유래하다", "ja": "由来する", "zh": "源于", "es": "derivar", "fr": "dériver", "de": "ableiten", "ru": "получать" } },
    { "word": "designate", "ipa": "ˈdɛzɪɡneɪt", "meanings": { "ko": "지정하다, 지명하다", "ja": "指定する", "zh": "指定", "es": "designar", "fr": "désigner", "de": "bezeichnen", "ru": "назначать" } },
    { "word": "detect", "ipa": "dɪˈtɛkt", "meanings": { "ko": "탐지하다, 발견하다", "ja": "検出する", "zh": "检测", "es": "detectar", "fr": "détecter", "de": "erkennen", "ru": "обнаруживать" } },
    { "word": "deviate", "ipa": "ˈdiːvieɪt", "meanings": { "ko": "벗어나다, 일탈하다", "ja": "逸脱する", "zh": "偏离", "es": "desviarse", "fr": "dévier", "de": "abweichen", "ru": "отклоняться" } },
    { "word": "devise", "ipa": "dɪˈvaɪz", "meanings": { "ko": "고안하다, 발명하다", "ja": "考案する", "zh": "设计", "es": "idear", "fr": "concevoir", "de": "entwickeln", "ru": "разрабатывать" } },
    { "word": "diminish", "ipa": "dɪˈmɪnɪʃ", "meanings": { "ko": "줄이다, 감소시키다", "ja": "減少させる", "zh": "减少", "es": "disminuir", "fr": "diminuer", "de": "verringern", "ru": "уменьшать" } },
    { "word": "discern", "ipa": "dɪˈsɜːrn", "meanings": { "ko": "식별하다, 알아보다", "ja": "見分ける", "zh": "辨别", "es": "discernir", "fr": "discerner", "de": "erkennen", "ru": "различать" } },
    { "word": "discrepancy", "ipa": "dɪˈskrɛpənsi", "meanings": { "ko": "불일치, 차이", "ja": "不一致", "zh": "差异", "es": "discrepancia", "fr": "divergence", "de": "Diskrepanz", "ru": "расхождение" } },
    { "word": "disperse", "ipa": "dɪˈspɜːrs", "meanings": { "ko": "흩뜨리다, 분산시키다", "ja": "分散させる", "zh": "分散", "es": "dispersar", "fr": "disperser", "de": "zerstreuen", "ru": "рассеивать" } },
    { "word": "disrupt", "ipa": "dɪsˈrʌpt", "meanings": { "ko": "방해하다, 혼란시키다", "ja": "妨害する", "zh": "扰乱", "es": "interrumpir", "fr": "perturber", "de": "stören", "ru": "нарушать" } },
    { "word": "distort", "ipa": "dɪˈstɔːrt", "meanings": { "ko": "왜곡하다", "ja": "歪曲する", "zh": "扭曲", "es": "distorsionar", "fr": "déformer", "de": "verzerren", "ru": "искажать" } },
    { "word": "document", "ipa": "ˈdɑːkjumɛnt", "meanings": { "ko": "기록하다, 문서", "ja": "文書", "zh": "文件", "es": "documentar", "fr": "documenter", "de": "dokumentieren", "ru": "документ" } },
    { "word": "dominant", "ipa": "ˈdɑːmɪnənt", "meanings": { "ko": "우세한, 지배적인", "ja": "支配的な", "zh": "主导的", "es": "dominante", "fr": "dominant", "de": "dominant", "ru": "доминирующий" } },
    { "word": "duplicate", "ipa": "ˈduːplɪkeɪt", "meanings": { "ko": "복제하다, 사본", "ja": "複製する", "zh": "复制", "es": "duplicar", "fr": "dupliquer", "de": "duplizieren", "ru": "дублировать" } },
    { "word": "elaborate", "ipa": "ɪˈlæbəreɪt", "meanings": { "ko": "정교한, 상세히 설명하다", "ja": "精巧な", "zh": "详尽的", "es": "elaborado", "fr": "élaborer", "de": "ausführlich", "ru": "разрабатывать" } },
    { "word": "elicit", "ipa": "ɪˈlɪsɪt", "meanings": { "ko": "이끌어내다, 유도하다", "ja": "引き出す", "zh": "引出", "es": "obtener", "fr": "susciter", "de": "entlocken", "ru": "вызывать" } },
    { "word": "emphasize", "ipa": "ˈɛmfəsaɪz", "meanings": { "ko": "강조하다", "ja": "強調する", "zh": "强调", "es": "enfatizar", "fr": "souligner", "de": "betonen", "ru": "подчеркивать" } },
    { "word": "empirical", "ipa": "ɪmˈpɪrɪkəl", "meanings": { "ko": "경험적인, 실증적인", "ja": "経験的な", "zh": "经验的", "es": "empírico", "fr": "empirique", "de": "empirisch", "ru": "эмпирический" } },
    { "word": "encounter", "ipa": "ɪnˈkaʊntər", "meanings": { "ko": "마주치다, 경험하다", "ja": "遭遇する", "zh": "遇到", "es": "encontrar", "fr": "rencontrer", "de": "begegnen", "ru": "сталкиваться" } },
    { "word": "equate", "ipa": "ɪˈkweɪt", "meanings": { "ko": "동일시하다, 같다고 생각하다", "ja": "等しいとみなす", "zh": "等同", "es": "equiparar", "fr": "assimiler", "de": "gleichsetzen", "ru": "приравнивать" } },
    { "word": "establish", "ipa": "ɪˈstæblɪʃ", "meanings": { "ko": "설립하다, 확립하다", "ja": "設立する", "zh": "建立", "es": "establecer", "fr": "établir", "de": "etablieren", "ru": "устанавливать" } },
    { "word": "ethical", "ipa": "ˈɛθɪkəl", "meanings": { "ko": "윤리적인, 도덕적인", "ja": "倫理的な", "zh": "道德的", "es": "ético", "fr": "éthique", "de": "ethisch", "ru": "этический" } },
    { "word": "evaluate", "ipa": "ɪˈvæljueɪt", "meanings": { "ko": "평가하다", "ja": "評価する", "zh": "评估", "es": "evaluar", "fr": "évaluer", "de": "bewerten", "ru": "оценивать" } },
    { "word": "evident", "ipa": "ˈɛvɪdənt", "meanings": { "ko": "분명한, 명백한", "ja": "明白な", "zh": "明显的", "es": "evidente", "fr": "évident", "de": "offensichtlich", "ru": "очевидный" } },
    { "word": "evoke", "ipa": "ɪˈvoʊk", "meanings": { "ko": "불러일으키다, 상기시키다", "ja": "呼び起こす", "zh": "唤起", "es": "evocar", "fr": "évoquer", "de": "hervorrufen", "ru": "вызывать" } },
    { "word": "exaggerate", "ipa": "ɪɡˈzædʒəreɪt", "meanings": { "ko": "과장하다", "ja": "誇張する", "zh": "夸大", "es": "exagerar", "fr": "exagérer", "de": "übertrieben", "ru": "преувеличивать" } },
    { "word": "exhibit", "ipa": "ɪɡˈzɪbɪt", "meanings": { "ko": "보여주다, 전시하다", "ja": "展示する", "zh": "展示", "es": "exhibir", "fr": "exposer", "de": "ausstellen", "ru": "выставлять" } },
    { "word": "exploit", "ipa": "ɪkˈsplɔɪt", "meanings": { "ko": "착취하다, 활용하다", "ja": "搾取する", "zh": "利用", "es": "explotar", "fr": "exploiter", "de": "ausbeuten", "ru": "эксплуатировать" } },
    { "word": "expose", "ipa": "ɪkˈspoʊz", "meanings": { "ko": "노출시키다, 폭로하다", "ja": "露出させる", "zh": "揭露", "es": "exponer", "fr": "exposer", "de": "entlarven", "ru": "разоблачать" } },
    { "word": "facilitate", "ipa": "fəˈsɪlɪteɪt", "meanings": { "ko": "용이하게 하다, 촉진하다", "ja": "促進する", "zh": "促进", "es": "facilitar", "fr": "faciliter", "de": "erleichtern", "ru": "облегчать" } },
    { "word": "fluctuate", "ipa": "ˈflʌktʃueɪt", "meanings": { "ko": "변동하다, 오르내리다", "ja": "変動する", "zh": "波动", "es": "fluctuar", "fr": "fluctuer", "de": "schwanken", "ru": "колебаться" } },
    { "word": "formulate", "ipa": "ˈfɔːrmjuleɪt", "meanings": { "ko": "공식화하다, 명확히 나타내다", "ja": "明確にする", "zh": "阐明", "es": "formular", "fr": "formuler", "de": "formulieren", "ru": "формулировать" } },
    { "word": "generate", "ipa": "ˈdʒɛnəreɪt", "meanings": { "ko": "생성하다, 발생시키다", "ja": "生成する", "zh": "生成", "es": "generar", "fr": "générer", "de": "erzeugen", "ru": "генерировать" } },
    { "word": "hypothesize", "ipa": "haɪˈpɑːθəsaɪz", "meanings": { "ko": "가설을 세우다", "ja": "仮説を立てる", "zh": "假设", "es": "hipotetizar", "fr": "hypothétiser", "de": "hypothetisieren", "ru": "выдвигать гипотезу" } },
    { "word": "identify", "ipa": "aɪˈdɛntɪfaɪ", "meanings": { "ko": "확인하다, 식별하다", "ja": "特定する", "zh": "识别", "es": "identificar", "fr": "identifier", "de": "identifizieren", "ru": "идентифицировать" } },
    { "word": "illustrate", "ipa": "ˈɪləstreɪt", "meanings": { "ko": "설명하다, 삽화를 넣다", "ja": "説明する", "zh": "说明", "es": "ilustrar", "fr": "illustrer", "de": "illustrieren", "ru": "иллюстрировать" } },
    { "word": "imply", "ipa": "ɪmˈplaɪ", "meanings": { "ko": "암시하다, 내포하다", "ja": "暗示する", "zh": "暗示", "es": "implicar", "fr": "impliquer", "de": "implizieren", "ru": "подразумевать" } },
    { "word": "incorporate", "ipa": "ɪnˈkɔːrpəreɪt", "meanings": { "ko": "통합하다, 포함하다", "ja": "組み入れる", "zh": "合并", "es": "incorporar", "fr": "incorporer", "de": "einbeziehen", "ru": "включать" } },
    { "word": "indicate", "ipa": "ˈɪndɪkeɪt", "meanings": { "ko": "나타내다, 지적하다", "ja": "示す", "zh": "表明", "es": "indicar", "fr": "indiquer", "de": "anzeigen", "ru": "указывать" } },
    { "word": "infer", "ipa": "ɪnˈfɜːr", "meanings": { "ko": "추론하다", "ja": "推測する", "zh": "推断", "es": "inferir", "fr": "inférer", "de": "folgern", "ru": "делать вывод" } },
    { "word": "interpret", "ipa": "ɪnˈtɜːrprɪt", "meanings": { "ko": "해석하다", "ja": "解釈する", "zh": "解释", "es": "interpretar", "fr": "interpréter", "de": "interpretieren", "ru": "интерпретировать" } },
    { "word": "intervene", "ipa": "ˌɪntərˈviːn", "meanings": { "ko": "개입하다, 중재하다", "ja": "介入する", "zh": "干预", "es": "intervenir", "fr": "intervenir", "de": "eingreifen", "ru": "вмешиваться" } },
    { "word": "legitimate", "ipa": "lɪˈdʒɪtɪmət", "meanings": { "ko": "합법적인, 정당한", "ja": "合法的な", "zh": "合法的", "es": "legítimo", "fr": "légitime", "de": "legitim", "ru": "законный" } },
    { "word": "manipulate", "ipa": "məˈnɪpjuleɪt", "meanings": { "ko": "조작하다, 다루다", "ja": "操作する", "zh": "操纵", "es": "manipular", "fr": "manipuler", "de": "manipulieren", "ru": "манипулировать" } },
    { "word": "mediate", "ipa": "ˈmiːdieɪt", "meanings": { "ko": "중재하다, 조정하다", "ja": "仲介する", "zh": "调解", "es": "mediar", "fr": "servir d'intermédiaire", "de": "vermitteln", "ru": "посредничать" } },
    { "word": "modify", "ipa": "ˈmɑːdɪfaɪ", "meanings": { "ko": "수정하다, 변경하다", "ja": "修正する", "zh": "修改", "es": "modificar", "fr": "modifier", "de": "modifizieren", "ru": "изменять" } },
    { "word": "monitor", "ipa": "ˈmɑːnɪtər", "meanings": { "ko": "감시하다, 관찰하다", "ja": "監視する", "zh": "监控", "es": "monitorear", "fr": "surveiller", "de": "überwachen", "ru": "контролировать" } },
    { "word": "negate", "ipa": "nɪˈɡeɪt", "meanings": { "ko": "무효화하다, 부정하다", "ja": "無効にする", "zh": "否定", "es": "negar", "fr": "annuler", "de": "aufheben", "ru": "отрицать" } },
    { "word": "notion", "ipa": "ˈnoʊʃən", "meanings": { "ko": "개념, 생각", "ja": "概念", "zh": "观念", "es": "noción", "fr": "notion", "de": "Begriff", "ru": "понятие" } },
    { "word": "objective", "ipa": "əbˈdʒɛktɪv", "meanings": { "ko": "객관적인, 목표", "ja": "客観的な", "zh": "客观的", "es": "objetivo", "fr": "objectif", "de": "objektiv", "ru": "объективный" } },
    { "word": "omit", "ipa": "oʊˈmɪt", "meanings": { "ko": "생략하다, 빠뜨리다", "ja": "省略する", "zh": "省略", "es": "omitir", "fr": "omettre", "de": "weglassen", "ru": "опускать" } },
    { "word": "orient", "ipa": "ˈɔːriɛnt", "meanings": { "ko": "지향하게 하다, 방향을 정하다", "ja": "方向づける", "zh": "定向", "es": "orientar", "fr": "orienter", "de": "orientieren", "ru": "ориентировать" } },
    { "word": "paradox", "ipa": "ˈpærədɑːks", "meanings": { "ko": "역설, 모순", "ja": "逆説", "zh": "悖论", "es": "paradoja", "fr": "paradoxe", "de": "Paradox", "ru": "парадокс" } },
    { "word": "perceive", "ipa": "pərˈsiːv", "meanings": { "ko": "인지하다, 인식하다", "ja": "知覚する", "zh": "感知", "es": "percibir", "fr": "percevoir", "de": "wahrnehmen", "ru": "воспринимать" } },
    { "word": "perspective", "ipa": "pərˈspɛktɪv", "meanings": { "ko": "관점, 시각", "ja": "視点", "zh": "视角", "es": "perspectiva", "fr": "perspective", "de": "Perspektive", "ru": "перспектива" } },
    { "word": "phenomenon", "ipa": "fəˈnɑːmɪnɑːn", "meanings": { "ko": "현상", "ja": "現象", "zh": "现象", "es": "fenómeno", "fr": "phénomène", "de": "Phänomen", "ru": "феномен" } },
    { "word": "precede", "ipa": "prɪˈsiːd", "meanings": { "ko": "앞서다, 선행하다", "ja": "先行する", "zh": "先于", "es": "preceder", "fr": "précéder", "de": "vorausgehen", "ru": "предшествовать" } },
    { "word": "presume", "ipa": "prɪˈzuːm", "meanings": { "ko": "추정하다, 가정하다", "ja": "推定する", "zh": "推定", "es": "presumir", "fr": "présumer", "de": "annehmen", "ru": "предполагать" } },
    { "word": "prevalent", "ipa": "ˈprɛvələnt", "meanings": { "ko": "널리 퍼져 있는, 일반적인", "ja": "普及している", "zh": "普遍的", "es": "prevalente", "fr": "prévalent", "de": "verbreitet", "ru": "преобладающий" } },
    { "word": "primary", "ipa": "ˈpraɪməri", "meanings": { "ko": "주요한, 기본적인", "ja": "主要な", "zh": "主要的", "es": "primario", "fr": "primaire", "de": "primär", "ru": "первичный" } },
    { "word": "principle", "ipa": "ˈprɪnsəpəl", "meanings": { "ko": "원칙, 원리", "ja": "原則", "zh": "原则", "es": "principio", "fr": "principe", "de": "Prinzip", "ru": "принцип" } },
    { "word": "proceed", "ipa": "proʊˈsiːd", "meanings": { "ko": "진행하다, 나아가다", "ja": "進む", "zh": "进行", "es": "proceder", "fr": "procéder", "de": "fortfahren", "ru": "продолжать" } },
    { "word": "project", "ipa": "ˈprɑːdʒɛkt", "meanings": { "ko": "계획, 프로젝트, 예상하다", "ja": "計画", "zh": "项目", "es": "proyecto", "fr": "projet", "de": "Projekt", "ru": "проект" } },
    { "word": "promote", "ipa": "prəˈmoʊt", "meanings": { "ko": "촉진하다, 홍보하다", "ja": "促進する", "zh": "促进", "es": "promover", "fr": "promouvoir", "de": "fördern", "ru": "способствовать" } },
    { "word": "pursue", "ipa": "pərˈsuː", "meanings": { "ko": "추구하다, 쫓다", "ja": "追求する", "zh": "追求", "es": "perseguir", "fr": "poursuivre", "de": "verfolgen", "ru": "преследовать" } },
    { "word": "range", "ipa": "reɪndʒ", "meanings": { "ko": "범위, 다양성", "ja": "範囲", "zh": "范围", "es": "rango", "fr": "gamme", "de": "Bereich", "ru": "диапазон" } },
    { "word": "ratio", "ipa": "ˈreɪʃioʊ", "meanings": { "ko": "비율", "ja": "比率", "zh": "比率", "es": "proporción", "fr": "ratio", "de": "Verhältnis", "ru": "соотношение" } },
    { "word": "rational", "ipa": "ˈræʃənəl", "meanings": { "ko": "합리적인, 이성적인", "ja": "合理的な", "zh": "理性的", "es": "racional", "fr": "rationnel", "de": "rational", "ru": "рациональный" } },
    { "word": "reinforce", "ipa": "ˌriːɪnˈfɔːrs", "meanings": { "ko": "강화하다, 보강하다", "ja": "強化する", "zh": "加强", "es": "reforzar", "fr": "renforcer", "de": "verstärken", "ru": "укреплять" } },
    { "word": "reject", "ipa": "rɪˈdʒɛkt", "meanings": { "ko": "거절하다, 거부하다", "ja": "拒否する", "zh": "拒绝", "es": "rechazar", "fr": "rejeter", "de": "ablehnen", "ru": "отвергать" } },
    { "word": "relevant", "ipa": "ˈrɛləvənt", "meanings": { "ko": "관련된, 적절한", "ja": "関連する", "zh": "相关的", "es": "relevante", "fr": "pertinent", "de": "relevant", "ru": "актуальный" } },
    { "word": "rely", "ipa": "rɪˈlaɪ", "meanings": { "ko": "~에 의존하다, 신뢰하다", "ja": "頼る", "zh": "依靠", "es": "confiar", "fr": "compter sur", "de": "sich verlassen", "ru": "полагаться" } },
    { "word": "resolve", "ipa": "rɪˈzɑːlv", "meanings": { "ko": "해결하다, 결심하다", "ja": "解決する", "zh": "解决", "es": "resolver", "fr": "résoudre", "de": "lösen", "ru": "решать" } },
    { "word": "retain", "ipa": "rɪˈteɪn", "meanings": { "ko": "유지하다, 보유하다", "ja": "保持する", "zh": "保留", "es": "retener", "fr": "retenir", "de": "behalten", "ru": "сохранять" } },
    { "word": "reveal", "ipa": "rɪˈviːl", "meanings": { "ko": "드러내다, 밝히다", "ja": "明らかにする", "zh": "揭示", "es": "revelar", "fr": "révéler", "de": "offenbaren", "ru": "раскрывать" } },
    { "word": "robust", "ipa": "roʊˈbʌst", "meanings": { "ko": "튼튼한, 강력한", "ja": "頑丈な", "zh": "健壮的", "es": "robusto", "fr": "robuste", "de": "robust", "ru": "крепкий" } },
    { "word": "simulate", "ipa": "ˈsɪmjuleɪt", "meanings": { "ko": "모의실험하다, ~인 체하다", "ja": "シミュレートする", "zh": "模拟", "es": "simular", "fr": "simuler", "de": "simulieren", "ru": "имитировать" } },
    { "word": "speculate", "ipa": "ˈspɛkjuleɪt", "meanings": { "ko": "추측하다, 사색하다", "ja": "推測する", "zh": "推测", "es": "especular", "fr": "spéculer", "de": "spekulieren", "ru": "размышлять" } },
    { "word": "subsequent", "ipa": "ˈsʌbsɪkwənt", "meanings": { "ko": "그 다음의, 뒤이은", "ja": "その後の", "zh": "随后的", "es": "subsiguiente", "fr": "ultérieur", "de": "nachfolgend", "ru": "последующий" } },
    { "word": "substantiate", "ipa": "səbˈstænʃieɪt", "meanings": { "ko": "입증하다, 실증하다", "ja": "実証する", "zh": "证实", "es": "sustanciar", "fr": "prouver", "de": "begründen", "ru": "обосновывать" } },
    { "word": "sufficient", "ipa": "səˈfɪʃənt", "meanings": { "ko": "충분한", "ja": "十分な", "zh": "足够的", "es": "suficiente", "fr": "suffisant", "de": "ausreichend", "ru": "достаточный" } },
    { "word": "supervise", "ipa": "ˈsuːpərvajz", "meanings": { "ko": "감독하다, 관리하다", "ja": "監督する", "zh": "监督", "es": "supervisar", "fr": "superviser", "de": "überwachen", "ru": "контролировать" } },
    { "word": "sustain", "ipa": "səˈsteɪn", "meanings": { "ko": "유지하다, 지탱하다", "ja": "維持する", "zh": "维持", "es": "sostener", "fr": "soutenir", "de": "aufrechterhalten", "ru": "поддерживать" } },
    { "word": "synthesize", "ipa": "ˈsɪnθəsaɪz", "meanings": { "ko": "종합하다, 합성하다", "ja": "統合する", "zh": "合成", "es": "sintetizar", "fr": "synthétiser", "de": "synthetisieren", "ru": "синтезировать" } },
    { "word": "underscore", "ipa": "ˌʌndərˈskɔːr", "meanings": { "ko": "강조하다, 밑줄을 긋다", "ja": "強調する", "zh": "强调", "es": "subrayar", "fr": "souligner", "de": "unterstreichen", "ru": "подчеркивать" } },
    { "word": "undertake", "ipa": "ˌʌndərˈteɪk", "meanings": { "ko": "착수하다, 맡다", "ja": "引き受ける", "zh": "承担", "es": "emprender", "fr": "entreprendre", "de": "übernehmen", "ru": "предпринимать" } },
    { "word": "validate", "ipa": "ˈvælɪdeɪt", "meanings": { "ko": "입증하다, 유효하게 하다", "ja": "検証する", "zh": "验证", "es": "validar", "fr": "valider", "de": "validieren", "ru": "проверять" } },
    { "word": "vary", "ipa": "ˈværi", "meanings": { "ko": "다르다, 다양하다", "ja": "異なる", "zh": "变化", "es": "variar", "fr": "varier", "de": "variieren", "ru": "варьироваться" } },
    { "word": "whereas", "ipa": "ˌwɛrˈæz", "meanings": { "ko": "~임에 반하여, ~이지만", "ja": "一方", "zh": "然而", "es": "mientras que", "fr": "tandis que", "de": "während", "ru": "тогда как" } },
    { "word": "abstract", "ipa": "ˈæbstrækt", "meanings": { "ko": "추상적인, 개요", "ja": "抽象的な", "zh": "抽象的", "es": "abstracto", "fr": "abstrait", "de": "abstrakt", "ru": "абстрактный" } },
    { "word": "accurate", "ipa": "ˈækjərət", "meanings": { "ko": "정확한", "ja": "正確な", "zh": "准确的", "es": "preciso", "fr": "précis", "de": "genau", "ru": "точный" } },
    { "word": "administer", "ipa": "ədˈmɪnɪstər", "meanings": { "ko": "관리하다, 집행하다", "ja": "管理する", "zh": "管理", "es": "administrar", "fr": "administrer", "de": "verwalten", "ru": "управлять" } },
    { "word": "allocate", "ipa": "ˈæləkeɪt", "meanings": { "ko": "할당하다, 배분하다", "ja": "割り当てる", "zh": "分配", "es": "asignar", "fr": "allouer", "de": "zuweisen", "ru": "выделять" } },
    { "word": "alteration", "ipa": "ˌɔːltəˈreɪʃən", "meanings": { "ko": "변경, 개조", "ja": "変更", "zh": "改变", "es": "alteración", "fr": "modification", "de": "Änderung", "ru": "изменение" } },
    { "word": "ambiguity", "ipa": "ˌæmbɪˈɡjuːəti", "meanings": { "ko": "모호함, 애매모호", "ja": "曖昧さ", "zh": "歧义", "es": "ambigüedad", "fr": "ambiguïté", "de": "Mehrdeutigkeit", "ru": "неоднозначность" } },
    { "word": "analogy", "ipa": "əˈnælədʒi", "meanings": { "ko": "유추, 비유", "ja": "類推", "zh": "类比", "es": "analogía", "fr": "analogie", "de": "Analogie", "ru": "аналогия" } },
    { "word": "apparent", "ipa": "əˈpærənt", "meanings": { "ko": "명백한, 분명한", "ja": "明白な", "zh": "明显", "es": "aparente", "fr": "apparent", "de": "offensichtlich", "ru": "очевидный" } },
    { "word": "appendix", "ipa": "əˈpɛndɪks", "meanings": { "ko": "부록, 맹장", "ja": "付録", "zh": "附录", "es": "apéndice", "fr": "annexe", "de": "Anhang", "ru": "приложение" } },
    { "word": "arbitrary", "ipa": "ˈɑːrbɪtrɛri", "meanings": { "ko": "임의적인, 독단적인", "ja": "恣意的な", "zh": "任意的", "es": "arbitrario", "fr": "arbitraire", "de": "willkürlich", "ru": "произвольный" } },
    { "word": "aspect", "ipa": "ˈæspɛkt", "meanings": { "ko": "측면, 양상", "ja": "側面", "zh": "方面", "es": "aspecto", "fr": "aspect", "de": "Aspekt", "ru": "аспект" } },
    { "word": "assertive", "ipa": "əˈsɜːrtɪv", "meanings": { "ko": "단호한, 자기주장이 강한", "ja": "断定的な", "zh": "自信的", "es": "asertivo", "fr": "assertif", "de": "durchsetzungsfähig", "ru": "настойчивый" } },
    { "word": "assumption", "ipa": "əˈsʌmpʃən", "meanings": { "ko": "가정, 추정", "ja": "仮定", "zh": "假设", "es": "suposición", "fr": "hypothèse", "de": "Annahme", "ru": "предположение" } },
    { "word": "authentic", "ipa": "ɔːˈθɛntɪk", "meanings": { "ko": "진정한, 진짜의", "ja": "本物の", "zh": "真实的", "es": "auténtico", "fr": "authentique", "de": "authentisch", "ru": "подлинный" } },
    { "word": "bias", "ipa": "ˈbaɪəs", "meanings": { "ko": "편견, 편향", "ja": "偏見", "zh": "偏见", "es": "sesgo", "fr": "biais", "de": "Voreingenommenheit", "ru": "предвзятость" } },
    { "word": "brevity", "ipa": "ˈbrɛvɪti", "meanings": { "ko": "간결함", "ja": "簡潔さ", "zh": "简洁", "es": "brevedad", "fr": "brièveté", "de": "Kürze", "ru": "краткость" } },
    { "word": "capacity", "ipa": "kəˈpæsɪti", "meanings": { "ko": "수용력, 능력", "ja": "能力", "zh": "容量", "es": "capacidad", "fr": "capacité", "de": "Kapazität", "ru": "вместимость" } },
    { "word": "capture", "ipa": "ˈkæptʃər", "meanings": { "ko": "포착하다, 사로잡다", "ja": "捕らえる", "zh": "捕获", "es": "capturar", "fr": "capturer", "de": "erfassen", "ru": "захватывать" } },
    { "word": "clarify", "ipa": "ˈklærɪfaɪ", "meanings": { "ko": "명확하게 하다, 분명히 하다", "ja": "明確にする", "zh": "澄清", "es": "clarificar", "fr": "clarifier", "de": "klären", "ru": "уточнять" } },
    { "word": "cognition", "ipa": "kɑːɡˈnɪʃən", "meanings": { "ko": "인지, 인식", "ja": "認知", "zh": "认知", "es": "cognición", "fr": "cognition", "de": "Kognition", "ru": "познание" } },
    { "word": "cohesive", "ipa": "koʊˈhiːsɪv", "meanings": { "ko": "응집력 있는, 결속력 있는", "ja": "結合力のある", "zh": "有凝聚力的", "es": "cohesivo", "fr": "cohésif", "de": "kohäsiv", "ru": "связанный" } },
    { "word": "commence", "ipa": "kəˈmɛns", "meanings": { "ko": "시작하다, 개시하다", "ja": "開始する", "zh": "开始", "es": "comenzar", "fr": "commencer", "de": "beginnen", "ru": "начинать" } },
    { "word": "compensate", "ipa": "ˈkɑːmpɛnseɪt", "meanings": { "ko": "보상하다, 보충하다", "ja": "補償する", "zh": "补偿", "es": "compensar", "fr": "compenser", "de": "kompensieren", "ru": "компенсировать" } },
    { "word": "complementary", "ipa": "ˌkɑːmplɪˈmɛntəri", "meanings": { "ko": "상호 보완적인", "ja": "補完的な", "zh": "互补的", "es": "complementario", "fr": "complémentaire", "de": "komplementär", "ru": "дополнительный" } },
    { "word": "comprise", "ipa": "kəmˈpraɪz", "meanings": { "ko": "~으로 구성되다, 포함하다", "ja": "構成する", "zh": "包含", "es": "comprender", "fr": "comprendre", "de": "umfassen", "ru": "включать" } },
    { "word": "concede", "ipa": "kənˈsiːd", "meanings": { "ko": "인정하다, 양보하다", "ja": "認める", "zh": "承认", "es": "conceder", "fr": "concéder", "de": "zugestehen", "ru": "уступать" } },
    { "word": "conjecture", "ipa": "kənˈdʒɛktʃər", "meanings": { "ko": "추측, 짐작", "ja": "推測", "zh": "推测", "es": "conjetura", "fr": "conjecture", "de": "Vermutung", "ru": "предположение" } },
    { "word": "connote", "ipa": "kəˈnoʊt", "meanings": { "ko": "함축하다, 암시하다", "ja": "含意する", "zh": "暗示", "es": "connotar", "fr": "connoter", "de": "konnotieren", "ru": "обозначать" } },
    { "word": "consensus", "ipa": "kənˈsɛnsəs", "meanings": { "ko": "합의, 의견 일치", "ja": "合意", "zh": "共识", "es": "consenso", "fr": "consensus", "de": "Konsens", "ru": "консенсус" } },
    { "word": "consequential", "ipa": "ˌkɑːnsɪˈkwɛnʃəl", "meanings": { "ko": "결과로 일어나는, 중요한", "ja": "結果として生じる", "zh": "重要的", "es": "consecuente", "fr": "conséquent", "de": "folgend", "ru": "значительный" } },
    { "word": "constitute", "ipa": "ˈkɑːnstɪtuːt", "meanings": { "ko": "~을 구성하다, 설립하다", "ja": "構成する", "zh": "构成", "es": "constituir", "fr": "constituer", "de": "bilden", "ru": "составлять" } },
    { "word": "contemporary", "ipa": "kənˈtɛmpərɛri", "meanings": { "ko": "현대의, 동시대의", "ja": "現代の", "zh": "当代的", "es": "contemporáneo", "fr": "contemporain", "de": "zeitgenössisch", "ru": "современный" } },
    { "word": "contextualize", "ipa": "kənˈtɛkstʃuəlaɪz", "meanings": { "ko": "맥락화하다", "ja": "文脈化する", "zh": "情境化", "es": "contextualizar", "fr": "contextualiser", "de": "kontextualisieren", "ru": "контекстуализировать" } },
    { "word": "contradictory", "ipa": "ˌkɑːntrəˈdɪktəri", "meanings": { "ko": "모순되는", "ja": "矛盾する", "zh": "矛盾的", "es": "contradictorio", "fr": "contradictoire", "de": "widersprüchlich", "ru": "противоречивый" } },
    { "word": "converge", "ipa": "kənˈvɜːrdʒ", "meanings": { "ko": "모이다, 집중하다", "ja": "収束する", "zh": "汇聚", "es": "converger", "fr": "converger", "de": "konvergieren", "ru": "сходиться" } },
    { "word": "corroborate", "ipa": "kəˈrɑːbəreɪt", "meanings": { "ko": "확증하다, 입증하다", "ja": "確証する", "zh": "证实", "es": "corroborar", "fr": "corroborer", "de": "bestätigen", "ru": "подтверждать" } },
    { "word": "credible", "ipa": "ˈkrɛdɪbəl", "meanings": { "ko": "신뢰할 수 있는, 믿을 만한", "ja": "信頼できる", "zh": "可信的", "es": "creíble", "fr": "crédible", "de": "glaubwürdig", "ru": "достоверный" } },
    { "word": "criterion", "ipa": "kraɪˈtɪəriən", "meanings": { "ko": "기준, 척도", "ja": "基準", "zh": "标准", "es": "criterio", "fr": "critère", "de": "Kriterium", "ru": "критерий" } },
    { "word": "culminate", "ipa": "ˈkʌlmɪneɪt", "meanings": { "ko": "절정에 달하다, ~으로 끝나다", "ja": "最高潮に達する", "zh": "达到高潮", "es": "culminar", "fr": "culminer", "de": "kulminieren", "ru": "завершаться" } },
    { "word": "cumulative", "ipa": "ˈkjuːmjələtɪv", "meanings": { "ko": "누적되는, 점증적인", "ja": "累積的な", "zh": "累积的", "es": "acumulativo", "fr": "cumulatif", "de": "kumulativ", "ru": "накопительный" } },
    { "word": "deductive", "ipa": "dɪˈdʌktɪv", "meanings": { "ko": "연역적인", "ja": "演繹的な", "zh": "演绎的", "es": "deductivo", "fr": "déductif", "de": "deduktiv", "ru": "дедуктивный" } },
    { "word": "deficient", "ipa": "dɪˈfɪʃənt", "meanings": { "ko": "부족한, 결함 있는", "ja": "欠陥のある", "zh": "不足的", "es": "deficiente", "fr": "déficient", "de": "mangelhaft", "ru": "недостаточный" } },
    { "word": "demographic", "ipa": "ˌdɛməˈɡræfɪk", "meanings": { "ko": "인구통계학적인", "ja": "人口統計学的な", "zh": "人口统计的", "es": "demográfico", "fr": "démographique", "de": "demografisch", "ru": "демографический" } },
    { "word": "denote", "ipa": "dɪˈnoʊt", "meanings": { "ko": "표시하다, 의미하다", "ja": "示す", "zh": "表示", "es": "denotar", "fr": "dénote", "de": "bezeichnen", "ru": "обозначать" } },
    { "word": "detrimental", "ipa": "ˌdɛtrɪˈmɛntl", "meanings": { "ko": "해로운, 유해한", "ja": "有害な", "zh": "有害的", "es": "perjudicial", "fr": "nuisible", "de": "schädlich", "ru": "вредный" } },
    { "word": "devote", "ipa": "dɪˈvoʊt", "meanings": { "ko": "헌신하다, 바치다", "ja": "捧げる", "zh": "奉献", "es": "dedicar", "fr": "dévouer", "de": "widmen", "ru": "посвящать" } },
    { "word": "differentiate", "ipa": "ˌdɪfəˈrɛnʃieɪt", "meanings": { "ko": "구별하다, 차별화하다", "ja": "区別する", "zh": "区分", "es": "diferenciar", "fr": "différencier", "de": "differenzieren", "ru": "различать" } },
    { "word": "dilemma", "ipa": "dɪˈlɛmə", "meanings": { "ko": "딜레마, 진퇴양난", "ja": "ジレンマ", "zh": "困境", "es": "dilema", "fr": "dilemme", "de": "Dilemma", "ru": "дилемма" } },
    { "word": "discrepancy", "ipa": "dɪˈskrɛpənsi", "meanings": { "ko": "불일치, 차이", "ja": "不一致", "zh": "差异", "es": "discrepancia", "fr": "divergence", "de": "Diskrepanz", "ru": "расхождение" } },
    { "word": "dissipate", "ipa": "ˈdɪsɪpeɪt", "meanings": { "ko": "흩어지게 하다, 낭비하다", "ja": "散逸させる", "zh": "消散", "es": "disipar", "fr": "dissiper", "de": "zerstreuen", "ru": "рассеивать" } },
    { "word": "diverge", "ipa": "daɪˈvɜːrdʒ", "meanings": { "ko": "갈라지다, 벗어나다", "ja": "分岐する", "zh": "分歧", "es": "divergir", "fr": "diverger", "de": "auseinandergehen", "ru": "расходиться" } },
    { "word": "doctrine", "ipa": "ˈdɑːktrɪn", "meanings": { "ko": "교리, 신조", "ja": "教義", "zh": "教义", "es": "doctrina", "fr": "doctrine", "de": "Doktrin", "ru": "доктрина" } },
    { "word": "drastic", "ipa": "ˈdræstɪk", "meanings": { "ko": "과감한, 극단적인", "ja": "劇的な", "zh": "严厉的", "es": "drástico", "fr": "drastique", "de": "drastisch", "ru": "радикальный" } },
    { "word": "durable", "ipa": "ˈdʊrəbəl", "meanings": { "ko": "내구성이 있는, 튼튼한", "ja": "耐久性のある", "zh": "耐用", "es": "duradero", "fr": "durable", "de": "langlebig", "ru": "долговечный" } },
    { "word": "eccentric", "ipa": "ɪkˈsɛntrɪk", "meanings": { "ko": "별난, 기이한", "ja": "風変わりな", "zh": "古怪的", "es": "excéntrico", "fr": "excentrique", "de": "exzentrisch", "ru": "эксцентричный" } },
    { "word": "eclectic", "ipa": "ɪˈklɛktɪk", "meanings": { "ko": "다방면에 걸친, 절충적인", "ja": "折衷的な", "zh": "兼容并蓄的", "es": "ecléctico", "fr": "éclectique", "de": "eklektisch", "ru": "эклектичный" } },
    { "word": "elucidate", "ipa": "ɪˈluːsɪdeɪt", "meanings": { "ko": "설명하다, 명료하게 하다", "ja": "解明する", "zh": "阐明", "es": "dilucidar", "fr": "élucider", "de": "erläutern", "ru": "разъяснять" } },
    { "word": "embrace", "ipa": "ɪmˈbreɪs", "meanings": { "ko": "포용하다, 받아들이다", "ja": "受け入れる", "zh": "拥抱", "es": "abrazar", "fr": "embrasser", "de": "umarmen", "ru": "обнимать" } },
    { "word": "emerge", "ipa": "ɪˈmɜːrdʒ", "meanings": { "ko": "나타나다, 부상하다", "ja": "現れる", "zh": "出现", "es": "emerger", "fr": "émerger", "de": "auftauchen", "ru": "появляться" } },
    { "word": "empirical", "ipa": "ɪmˈpɪrɪkəl", "meanings": { "ko": "경험적인, 실증적인", "ja": "経験的な", "zh": "经验的", "es": "empírico", "fr": "empirique", "de": "empirisch", "ru": "эмпирический" } },
    { "word": "endeavor", "ipa": "ɪnˈdɛvər", "meanings": { "ko": "노력, 노력하다", "ja": "努力", "zh": "努力", "es": "esfuerzo", "fr": "s'efforcer", "de": "Bemühung", "ru": "стараться" } },
    { "word": "endorse", "ipa": "ɪnˈdɔːrs", "meanings": { "ko": "승인하다, 지지하다", "ja": "支持する", "zh": "认可", "es": "respaldar", "fr": "approuver", "de": "befürworten", "ru": "одобрять" } },
    { "word": "engender", "ipa": "ɪnˈdʒɛndər", "meanings": { "ko": "야기하다, 발생시키다", "ja": "引き起こす", "zh": "产生", "es": "engendrar", "fr": "engendrer", "de": "hervorrufen", "ru": "порождать" } },
    { "word": "encompass", "ipa": "ɪnˈkʌmpəs", "meanings": { "ko": "포함하다, 망라하다", "ja": "網羅する", "zh": "包含", "es": "abarcar", "fr": "englober", "de": "umfassen", "ru": "охватывать" } },
    { "word": "equitable", "ipa": "ˈɛkwɪtəbəl", "meanings": { "ko": "공정한, 공평한", "ja": "公平な", "zh": "公平的", "es": "equitativo", "fr": "équitable", "de": "gerecht", "ru": "справедливый" } },
    { "word": "erroneous", "ipa": "ɪˈroʊniəs", "meanings": { "ko": "잘못된, 틀린", "ja": "誤った", "zh": "错误的", "es": "erróneo", "fr": "erroné", "de": "fehlerhaft", "ru": "ошибочный" } },
    { "word": "exacerbate", "ipa": "ɪɡˈzæsərbeɪt", "meanings": { "ko": "악화시키다", "ja": "悪化させる", "zh": "加剧", "es": "exacerbar", "fr": "exacerber", "de": "verschlimmern", "ru": "усугублять" } },
    { "word": "exclude", "ipa": "ɪkˈskluːd", "meanings": { "ko": "제외하다, 배제하다", "ja": "排除する", "zh": "排除", "es": "excluir", "fr": "exclure", "de": "ausschließen", "ru": "исключать" } },
    { "word": "exhaustive", "ipa": "ɪɡˈzɔːstɪv", "meanings": { "ko": "철저한, 완전한", "ja": "徹底的な", "zh": "详尽的", "es": "exhaustivo", "fr": "exhaustif", "de": "erschöpfend", "ru": "исчерпывающий" } },
    { "word": "explicit", "ipa": "ɪkˈsplɪsɪt", "meanings": { "ko": "명백한, 명시적인", "ja": "明確な", "zh": "明确的", "es": "explícito", "fr": "explicite", "de": "explizit", "ru": "явный" } },
    { "word": "fabricate", "ipa": "ˈfæbrɪkeɪt", "meanings": { "ko": "위조하다, 제작하다", "ja": "捏造する", "zh": "捏造", "es": "fabricar", "fr": "fabriquer", "de": "fälschen", "ru": "фабриковать" } },
    { "word": "foresee", "ipa": "fɔːrˈsiː", "meanings": { "ko": "예견하다, 내다보다", "ja": "予見する", "zh": "预见", "es": "prever", "fr": "prévoir", "de": "vorhersehen", "ru": "предвидеть" } },
    { "word": "heterogeneous", "ipa": "ˌhɛtərəˈdʒiːniəs", "meanings": { "ko": "이질적인, 다양한", "ja": "異種の", "zh": "异质的", "es": "heterogéneo", "fr": "hétérogène", "de": "heterogen", "ru": "гетерогенный" } },
    { "word": "homogeneous", "ipa": "ˌhoʊməˈdʒiːniəs", "meanings": { "ko": "동질적인", "ja": "同種の", "zh": "同质的", "es": "homogéneo", "fr": "homogène", "de": "homogen", "ru": "однородный" } },
    { "word": "hypothesis", "ipa": "haɪˈpɑːθəsɪs", "meanings": { "ko": "가설", "ja": "仮説", "zh": "假设", "es": "hipótesis", "fr": "hypothèse", "de": "Hypothese", "ru": "гипотеза" } },
    { "word": "imminent", "ipa": "ˈɪmɪnənt", "meanings": { "ko": "임박한, 곧 닥쳐올", "ja": "差し迫った", "zh": "即将发生的", "es": "inminente", "fr": "imminent", "de": "bevorstehend", "ru": "неизбежный" } },
    { "word": "implicit", "ipa": "ɪmˈplɪsɪt", "meanings": { "ko": "암묵적인, 내포된", "ja": "暗黙の", "zh": "含蓄的", "es": "implícito", "fr": "implicite", "de": "implizit", "ru": "неявный" } },
    { "word": "incidental", "ipa": "ˌɪnsɪˈdɛntl", "meanings": { "ko": "부수적인, 우연한", "ja": "付随的な", "zh": "附带的", "es": "incidental", "fr": "accessoire", "de": "zufällig", "ru": "случайный" } },
    { "word": "incline", "ipa": "ɪnˈklaɪn", "meanings": { "ko": "~하는 경향이 있다, 기울다", "ja": "傾く", "zh": "倾向于", "es": "inclinar", "fr": "incliner", "de": "neigen", "ru": "склоняться" } },
    { "word": "inconclusive", "ipa": "ˌɪnkənˈkluːsɪv", "meanings": { "ko": "결정적이지 않은, 불확실한", "ja": "結論の出ない", "zh": "不确定的", "es": "inconcluso", "fr": "peu concluant", "de": "nicht schlüssig", "ru": "неубедительный" } },
    { "word": "indigenous", "ipa": "ɪnˈdɪdʒɪnəs", "meanings": { "ko": "원산의, 토착의", "ja": "固有の", "zh": "本地的", "es": "indígena", "fr": "indigène", "de": "einheimisch", "ru": "коренной" } },
    { "word": "inevitable", "ipa": "ɪnˈɛvɪtəbəl", "meanings": { "ko": "피할 수 없는, 불가피한", "ja": "避けられない", "zh": "不可避免的", "es": "inevitable", "fr": "inévitable", "de": "unvermeidlich", "ru": "неизбежный" } },
    { "word": "inference", "ipa": "ˈɪnfərəns", "meanings": { "ko": "추론", "ja": "推論", "zh": "推断", "es": "inferencia", "fr": "inférence", "de": "Schlussfolgerung", "ru": "вывод" } },
    { "word": "inherent", "ipa": "ɪnˈhɪrənt", "meanings": { "ko": "내재하는, 본질적인", "ja": "固有の", "zh": "固有的", "es": "inherente", "fr": "inhérent", "de": "inhärent", "ru": "присущий" } },
    { "word": "inhibit", "ipa": "ɪnˈhɪbɪt", "meanings": { "ko": "억제하다, 방해하다", "ja": "抑制する", "zh": "抑制", "es": "inhibir", "fr": "inhiber", "de": "hemmen", "ru": "подавлять" } },
    { "word": "initiate", "ipa": "ɪˈnɪʃieɪt", "meanings": { "ko": "시작하다, 개시하다", "ja": "開始する", "zh": "启动", "es": "iniciar", "fr": "initier", "de": "initiieren", "ru": "инициировать" } },
    { "word": "integral", "ipa": "ˈɪntɪɡrəl", "meanings": { "ko": "필수적인, 완전한", "ja": "不可欠な", "zh": "不可或缺的", "es": "integral", "fr": "intégral", "de": "wesentlich", "ru": "неотъемлемый" } },
    { "word": "integrate", "ipa": "ˈɪntɪɡreɪt", "meanings": { "ko": "통합하다", "ja": "統合する", "zh": "整合", "es": "integrar", "fr": "intégrer", "de": "integrieren", "ru": "интегрировать" } },
    { "word": "interact", "ipa": "ˌɪntərˈækt", "meanings": { "ko": "상호작용하다", "ja": "相互作用する", "zh": "互动", "es": "interactuar", "fr": "interagir", "de": "interagieren", "ru": "взаимодействовать" } },
    { "word": "interpretive", "ipa": "ɪnˈtɜːrprɪtɪv", "meanings": { "ko": "해석적인", "ja": "解釈的な", "zh": "解释性的", "es": "interpretativo", "fr": "interprétatif", "de": "interpretativ", "ru": "интерпретационный" } },
    { "word": "intrinsic", "ipa": "ɪnˈtrɪnsɪk", "meanings": { "ko": "고유한, 본질적인", "ja": "本質的な", "zh": "固有的", "es": "intrínseco", "fr": "intrinsèque", "de": "intrinsisch", "ru": "внутренний" } },
    { "word": "invoke", "ipa": "ɪnˈvoʊk", "meanings": { "ko": "들먹이다, 빌다", "ja": "呼び起こす", "zh": "援引", "es": "invocar", "fr": "invoquer", "de": "anrufen", "ru": "призывать" } },
    { "word": "likewise", "ipa": "ˈlaɪkwaɪz", "meanings": { "ko": "마찬가지로", "ja": "同様に", "zh": "同样", "es": "asimismo", "fr": "de même", "de": "ebenfalls", "ru": "аналогично" } },
    { "word": "marginal", "ipa": "ˈmɑːrdʒɪnəl", "meanings": { "ko": "미미한, 한계의", "ja": "わずかな", "zh": "边缘的", "es": "marginal", "fr": "marginal", "de": "marginal", "ru": "маргинальный" } },
    { "word": "metaphor", "ipa": "ˈmɛtəfɔːr", "meanings": { "ko": "은유", "ja": "比喩", "zh": "比喻", "es": "metáfora", "fr": "métaphore", "de": "Metapher", "ru": "метафора" } },
    { "word": "minimal", "ipa": "ˈmɪnɪməl", "meanings": { "ko": "최소한의", "ja": "最小限の", "zh": "最小的", "es": "mínimo", "fr": "minimal", "de": "minimal", "ru": "минимальный" } },
    { "word": "mitigate", "ipa": "ˈmɪtɪɡeɪt", "meanings": { "ko": "완화시키다, 경감하다", "ja": "緩和する", "zh": "减轻", "es": "mitigar", "fr": "atténuer", "de": "mildern", "ru": "смягчать" } },
    { "word": "mutual", "ipa": "ˈmjuːtʃuəl", "meanings": { "ko": "상호적인, 공동의", "ja": "相互の", "zh": "相互的", "es": "mutuo", "fr": "mutuel", "de": "gegenseitig", "ru": "взаимный" } },
    { "word": "notwithstanding", "ipa": "ˌnɑːtwɪθˈstændɪŋ", "meanings": { "ko": "~에도 불구하고", "ja": "~にもかかわらず", "zh": "尽管", "es": "a pesar de", "fr": "nonobstant", "de": "trotz", "ru": "несмотря на" } },
    { "word": "offset", "ipa": "ˈɔːfsɛt", "meanings": { "ko": "상쇄하다, 벌충하다", "ja": "相殺する", "zh": "抵消", "es": "compensar", "fr": "compenser", "de": "ausgleichen", "ru": "компенсировать" } },
    { "word": "paradigm", "ipa": "ˈpærədaɪm", "meanings": { "ko": "패러다임, 전형", "ja": "パラダイム", "zh": "范式", "es": "paradigma", "fr": "paradigme", "de": "Paradigma", "ru": "парадигма" } },
    { "word": "parameter", "ipa": "pəˈræmɪtər", "meanings": { "ko": "매개변수, 한계", "ja": "パラメータ", "zh": "参数", "es": "parámetro", "fr": "paramètre", "de": "Parameter", "ru": "параметр" } },
    { "word": "pervasive", "ipa": "pərˈveɪsɪv", "meanings": { "ko": "널리 퍼져 있는, 스며드는", "ja": "普及している", "zh": "普遍的", "es": "penetrante", "fr": "envahissant", "de": "durchdringend", "ru": "всепроникающий" } },
    { "word": "precedent", "ipa": "ˈprɛsɪdənt", "meanings": { "ko": "선례, 전례", "ja": "前例", "zh": "先例", "es": "precedente", "fr": "précédent", "de": "Präzedenzfall", "ru": "прецедент" } },
    { "word": "preclude", "ipa": "prɪˈkluːd", "meanings": { "ko": "방해하다, 불가능하게 하다", "ja": "妨げる", "zh": "排除", "es": "excluir", "fr": "empêcher", "de": "ausschließen", "ru": "исключать" } },
    { "word": "predominant", "ipa": "prɪˈdɑːmɪnənt", "meanings": { "ko": "지배적인, 우세한", "ja": "優勢な", "zh": "主要的", "es": "predominante", "fr": "prédominant", "de": "vorherrschend", "ru": "преобладающий" } },
    { "word": "prescribe", "ipa": "prɪˈskraɪb", "meanings": { "ko": "처방하다, 규정하다", "ja": "処方する", "zh": "规定", "es": "prescribir", "fr": "prescrire", "de": "verschreiben", "ru": "предписывать" } },
    { "word": "presuppose", "ipa": "ˌpriːsəˈpoʊz", "meanings": { "ko": "전제하다, 미리 가정하다", "ja": "前提とする", "zh": "预设", "es": "presuponer", "fr": "présupposer", "de": "voraussetzen", "ru": "предполагать" } },
    { "word": "prevail", "ipa": "prɪˈveɪl", "meanings": { "ko": "만연하다, 우세하다", "ja": "普及する", "zh": "盛行", "es": "prevalecer", "fr": "prévaloir", "de": "vorherrschen", "ru": "преобладать" } },
    { "word": "profound", "ipa": "prəˈfaʊnd", "meanings": { "ko": "심오한, 깊은", "ja": "深遠な", "zh": "深刻的", "es": "profundo", "fr": "profond", "de": "tiefgreifend", "ru": "глубокий" } },
    { "word": "proliferation", "ipa": "prəˌlɪfəˈreɪʃən", "meanings": { "ko": "확산, 증식", "ja": "拡散", "zh": "扩散", "es": "proliferación", "fr": "prolifération", "de": "Proliferation", "ru": "распространение" } },
    { "word": "protocol", "ipa": "ˈproʊtəkɑːl", "meanings": { "ko": "규약, 의정서", "ja": "プロトコル", "zh": "协议", "es": "protocolo", "fr": "protocole", "de": "Protokoll", "ru": "протокол" } },
    { "word": "qualitative", "ipa": "ˈkwɑːlɪteɪtɪv", "meanings": { "ko": "질적인", "ja": "質的な", "zh": "定性的", "es": "cualitativo", "fr": "qualitatif", "de": "qualitativ", "ru": "качественный" } },
    { "word": "quantify", "ipa": "ˈkwɑːntɪfaɪ", "meanings": { "ko": "정량화하다, 수량화하다", "ja": "定量化する", "zh": "量化", "es": "cuantificar", "fr": "quantifier", "de": "quantifizieren", "ru": "количественно оценивать" } },
    { "word": "radical", "ipa": "ˈrædɪkəl", "meanings": { "ko": "근본적인, 급진적인", "ja": "根本的な", "zh": "激进的", "es": "radical", "fr": "radical", "de": "radikal", "ru": "радикальный" } },
    { "word": "rationalize", "ipa": "ˈræʃənəlaɪz", "meanings": { "ko": "합리화하다", "ja": "合理化する", "zh": "合理化", "es": "racionalizar", "fr": "rationaliser", "de": "rationalisieren", "ru": "рационализировать" } },
    { "word": "reconcile", "ipa": "ˈrɛkənsaɪl", "meanings": { "ko": "화해시키다, 조화시키다", "ja": "和解させる", "zh": "调和", "es": "reconciliar", "fr": "réconcilier", "de": "versöhnen", "ru": "примирять" } },
    { "word": "refer", "ipa": "rɪˈfɜːr", "meanings": { "ko": "언급하다, 참조하다", "ja": "参照する", "zh": "提及", "es": "referir", "fr": "se référer", "de": "sich beziehen", "ru": "ссылаться" } },
    { "word": "refute", "ipa": "rɪˈfjuːt", "meanings": { "ko": "반박하다, 논박하다", "ja": "反駁する", "zh": "驳斥", "es": "refutar", "fr": "réfuter", "de": "widerlegen", "ru": "опровергать" } },
    { "word": "reiterate", "ipa": "riˈɪtəreɪt", "meanings": { "ko": "반복해서 말하다", "ja": "繰り返す", "zh": "重申", "es": "reiterar", "fr": "réitérer", "de": "wiederholen", "ru": "повторять" } },
    { "word": "render", "ipa": "ˈrɛndər", "meanings": { "ko": "~하게 만들다, 제공하다", "ja": "する", "zh": "使成为", "es": "hacer", "fr": "rendre", "de": "machen", "ru": "оказывать" } },
    { "word": "replicate", "ipa": "ˈrɛplɪkeɪt", "meanings": { "ko": "복제하다, 되풀이하다", "ja": "複製する", "zh": "复制", "es": "replicar", "fr": "répliquer", "de": "replizieren", "ru": "копировать" } },
    { "word": "represent", "ipa": "ˌrɛprɪˈzɛnt", "meanings": { "ko": "나타내다, 대표하다", "ja": "代表する", "zh": "代表", "es": "representar", "fr": "représenter", "de": "repräsentieren", "ru": "представлять" } },
    { "word": "resilient", "ipa": "rɪˈzɪliənt", "meanings": { "ko": "회복력 있는, 탄력 있는", "ja": "弾力性のある", "zh": "有弹性的", "es": "resiliente", "fr": "résilient", "de": "widerstandsfähig", "ru": "устойчивый" } },
    { "word": "resonate", "ipa": "ˈrɛzəneɪt", "meanings": { "ko": "울려 퍼지다, 공명하다", "ja": "共鳴する", "zh": "共鸣", "es": "resonar", "fr": "résonner", "de": "resonieren", "ru": "резонировать" } },
    { "word": "scrutinize", "ipa": "ˈskruːtənaɪz", "meanings": { "ko": "세밀히 조사하다", "ja": "綿密に調べる", "zh": "仔细审查", "es": "examinar", "fr": "scruter", "de": "prüfen", "ru": "тщательно изучать" } },
    { "word": "segment", "ipa": "ˈsɛɡmənt", "meanings": { "ko": "부분, 단편", "ja": "部分", "zh": "部分", "es": "segmento", "fr": "segment", "de": "Segment", "ru": "сегмент" } },
    { "word": "sequence", "ipa": "ˈsiːkwəns", "meanings": { "ko": "순서, 연속", "ja": "順序", "zh": "序列", "es": "secuencia", "fr": "séquence", "de": "Sequenz", "ru": "последовательность" } },
    { "word": "significant", "ipa": "sɪɡˈnɪfɪkənt", "meanings": { "ko": "중요한, 상당한", "ja": "重要な", "zh": "重要的", "es": "significativo", "fr": "significatif", "de": "bedeutend", "ru": "значительный" } },
    { "word": "skepticism", "ipa": "ˈskɛptɪsɪzəm", "meanings": { "ko": "회의론, 회의적인 태도", "ja": "懐疑主義", "zh": "怀疑论", "es": "escepticismo", "fr": "scepticisme", "de": "Skepsis", "ru": "скептицизм" } },
    { "word": "solely", "ipa": "ˈsoʊlli", "meanings": { "ko": "오로지, 단독으로", "ja": "もっぱら", "zh": "仅仅", "es": "solamente", "fr": "uniquement", "de": "ausschließlich", "ru": "исключительно" } },
    { "word": "somewhat", "ipa": "ˈsʌmwʌt", "meanings": { "ko": "어느 정도, 다소", "ja": "いくらか", "zh": "有点", "es": "algo", "fr": "un peu", "de": "etwas", "ru": "несколько" } },
    { "word": "sparse", "ipa": "spɑːrs", "meanings": { "ko": "희박한, 드문", "ja": "まばらな", "zh": "稀疏的", "es": "escaso", "fr": "clairsemé", "de": "spärlich", "ru": "разреженный" } },
    { "word": "specimen", "ipa": "ˈspɛsɪmən", "meanings": { "ko": "표본, 견본", "ja": "標本", "zh": "样本", "es": "espécimen", "fr": "spécimen", "de": "Exemplar", "ru": "образец" } },
    { "word": "stagnant", "ipa": "ˈstæɡnənt", "meanings": { "ko": "정체된, 침체된", "ja": "停滞した", "zh": "停滞的", "es": "estancado", "fr": "stagnant", "de": "stagnierend", "ru": "застойный" } },
    { "word": "subtle", "ipa": "ˈsʌtl", "meanings": { "ko": "미묘한, 교묘한", "ja": "微妙な", "zh": "微妙的", "es": "sutil", "fr": "subtil", "de": "subtil", "ru": "тонкий" } },
    { "word": "succinct", "ipa": "səkˈsɪŋkt", "meanings": { "ko": "간결한, 명확한", "ja": "簡潔な", "zh": "简洁的", "es": "conciso", "fr": "succinct", "de": "prägnant", "ru": "лаконичный" } },
    { "word": "superficial", "ipa": "ˌsuːpərˈfɪʃəl", "meanings": { "ko": "피상적인, 표면적인", "ja": "表面的な", "zh": "肤浅的", "es": "superficial", "fr": "superficiel", "de": "oberflächlich", "ru": "поверхностный" } },
    { "word": "supplement", "ipa": "ˈsʌplɪmənt", "meanings": { "ko": "보충하다, 보충물", "ja": "補足する", "zh": "补充", "es": "suplemento", "fr": "compléter", "de": "ergänzen", "ru": "дополнение" } },
    { "word": "surpass", "ipa": "sərˈpæs", "meanings": { "ko": "능가하다, 초과하다", "ja": "上回る", "zh": "超越", "es": "superar", "fr": "dépasser", "de": "übertreffen", "ru": "превосходить" } },
    { "word": "susceptible", "ipa": "səˈsɛptəbəl", "meanings": { "ko": "~에 취약한, 영향을 받기 쉬운", "ja": "影響を受けやすい", "zh": "易受影响的", "es": "susceptible", "fr": "susceptible", "de": "anfällig", "ru": "восприимчивый" } },
    { "word": "tangible", "ipa": "ˈtændʒəbəl", "meanings": { "ko": "실체적인, 만질 수 있는", "ja": "有形の", "zh": "有形的", "es": "tangible", "fr": "tangible", "de": "greifbar", "ru": "осязаемый" } },
    { "word": "tentative", "ipa": "ˈtɛntətɪv", "meanings": { "ko": "잠정적인, 시험적인", "ja": "暫定的な", "zh": "暂定的", "es": "tentativo", "fr": "provisoire", "de": "vorläufig", "ru": "предварительный" } },
    { "word": "undergo", "ipa": "ˌʌndərˈɡoʊ", "meanings": { "ko": "겪다, 경험하다", "ja": "経験する", "zh": "经历", "es": "someterse a", "fr": "subir", "de": "durchmachen", "ru": "подвергаться" } },
    { "word": "unprecedented", "ipa": "ʌnˈprɛsɪdɛntɪd", "meanings": { "ko": "전례 없는", "ja": "前例のない", "zh": "前所未有的", "es": "sin precedentes", "fr": "sans précédent", "de": "beispiellos", "ru": "беспрецедентный" } },
    { "word": "validity", "ipa": "vəˈlɪdəti", "meanings": { "ko": "유효성, 타당성", "ja": "妥当性", "zh": "有效性", "es": "validez", "fr": "validité", "de": "Gültigkeit", "ru": "действительность" } },
    { "word": "versatile", "ipa": "ˈvɜːrsətəl", "meanings": { "ko": "다재다능한, 다용도의", "ja": "多才な", "zh": "多才多艺的", "es": "versátil", "fr": "polyvalent", "de": "vielseitig", "ru": "универсальный" } },
    { "word": "viable", "ipa": "ˈvaɪəbəl", "meanings": { "ko": "실행 가능한, 생존 가능한", "ja": "実行可能な", "zh": "可行的", "es": "viable", "fr": "viable", "de": "machbar", "ru": "жизнеспособный" } },
    { "word": "warrant", "ipa": "ˈwɔːrənt", "meanings": { "ko": "정당화하다, 영장", "ja": "保証する", "zh": "保证", "es": "garantizar", "fr": "justifier", "de": "rechtfertigen", "ru": "гарантировать" } },
    { "word": "yield", "ipa": "jiːld", "meanings": { "ko": "산출하다, 양보하다, 수확량", "ja": "産出する", "zh": "产量", "es": "rendimiento", "fr": "rendement", "de": "Ertrag", "ru": "урожай" } }
  ];
